name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.GITHUB_TOKEN }}
      # - name: Build and Push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./android
      #     file: ./android/Dockerfile
      #     tags: ghcr.io/lingjhf/flutter-android:3.27.1
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
